
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'bjj_rank'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'bjj_rank'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  bjj_rank:
    core:
      +materialized: view
      +schema: core

seeds:
  bjj_rank:
    +enabled: true
    +schema: seed

    raw_matches:
      +column_types:
        id: int
        event_id: int
        user_id: int
        opponent_id: int
        is_winner: boolean
        mmr_change: int
        match_at: timestamp
    
    raw_events:
      +column_types:
        id: int
        name: varchar(64)
        info: varchar(128)
        address: varchar(128)
        event_begin_at: timestamp
        event_end_at: timestamp

    raw_users:
      +column_types:
        id: int
        username: varchar(32)
        created_at: timestamp
        
    raw_users_info:
      +column_types:
        id: int
        firstname: varchar(32)
        lastname: varchar(32)
        email: varchar(32)